export const VIDEO_MATCHES_LOAD = "VIDEO_MATCHES_LOAD";
export const VIDEO_MATCH_LIFE = "VIDEO_MATCH_LIFE";
export const LOADER_DISPLAY_ON = "LOADER_DISPLAY_ON";
export const LOADER_DISPLAY_OFF = "LOADER_DISPLAY_OFF";
export const ERROR_DISPLAY_ON = "ERROR_DISPLAY_ON";
export const ERROR_DISPLAY_OFF = "ERROR_DISPLAY_OFF";
export const CHOOSE_CHAMP = "CHOOSE_CHAMP";
