import uniqid from "uniqid";
export const Btns = [
    { id: uniqid(), liga: "ENGLAND: Premier League" },
    { id: uniqid(), liga: "ENGLAND: League Cup" },
    { id: uniqid(), liga: "ENGLAND: FA Cup" },
    { id: uniqid(), liga: "SPAIN: La Liga" },
    { id: uniqid(), liga: "SPAIN: National cup" },
    { id: uniqid(), liga: "SPAIN: La Liga2" },
    { id: uniqid(), liga: "FRANCE: National cup" },
    { id: uniqid(), liga: "FRANCE: Ligue 1" },
    { id: uniqid(), liga: "ITALY: Serie A" },
    { id: uniqid(), liga: "GERMANY: Bundesliga" },
    { id: uniqid(), liga: "PORTUGAL: Liga Portugal" },
    { id: uniqid(), liga: "MEXICO: Clausura" },
    { id: uniqid(), liga: "MEXICO: Clausura" },
    { id: uniqid(), liga: "AFRICA NATIONS CUP: Group A" },
    { id: uniqid(), liga: "INDIA: ISL" },
    { id: uniqid(), liga: "QATAR: Stars League" },
    { id: uniqid(), liga: "MEXICO: Liga de Expansion, Clausura" },
  ];